name: Haddock

# on:
#   push:
#     branches: [ master ]
on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Haskell
      uses: actions/setup-haskell@v1
      with:
        ghc-version: '9.6.2'

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.stack
          ./.stack-work
        key: ${{ runner.os }}-stack

    - name: Install dependencies
      run: |
        stack setup
        stack build --only-dependencies

    - name: Build documentation
      run: |
        stack haddock --no-haddock-deps

    - name: Publish documentation
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages  # The branch the action should deploy to.
        folder: .stack-work/dist/x86_64-linux/Cabal-3.2.1.0/doc  # The folder the action should deploy.
